
const chats = [
  {
    "id": 1,
    "profile": "https://i.ibb.co/r0mGfL0/Ellipse-121.png",
    "username": "Jordan ",
    "description": "Hii!",
    "dateTime": "13:10",
    "verified": "true",
    "typing": "false",
    "chats": "1",
  },
  {
    "id": 2,
    "profile": "https://i.ibb.co/SrnZbdY/Ellipse-122.png",
    "username": "Tim",
    "description": "Hii!",
    "dateTime": "13:10",
    "verified": "true",
    "typing": "false",
    "chats": "0",
  },
  {
    "id": 3,
    "profile": "https://i.ibb.co/vVrTFtg/Ellipse-c121.png",
    "username": "James",
    "description": "Typing...",
    "dateTime": "13:10",
    "verified": "false",
    "typing": "true",
    "chats": "9+",
  },
  {
    "id": 4,
    "profile": "https://images.unsplash.com/photo-1485178575877-1a13bf489dfe?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1982&q=80",
    "username": "User 4",
    "description": "Hello",
    "dateTime": "16:10",
    "verified": "false",
    "typing": "false",
    "chats": "5",
  },
  {
    "id": 5,
    "profile": "https://images.unsplash.com/photo-1525254574692-686fd35b6ab1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=935&q=80",
    "username": "User 5",
    "description": "Hello",
    "dateTime": "13:56",
    "verified": "true",
    "typing": "false",
    "chats": "0",
  },

  {
    "id": 6,
    "profile": "https://i.ibb.co/WcLR6s1/Rectangle-454.png",
    "username": "Tony Stark",
    "description": "Hii!",
    "dateTime": "13:10",
    "verified": "true",
    "typing": "false",
    "chats": "1",
  },
  {
    "id": 7,
    "profile": "https://i.ibb.co/hRBDw32/Ellipse-2.png",
    "username": "User random",
    "description": "Typing...",
    "dateTime": "13:10",
    "verified": "false",
    "typing": "true",
    "chats": "9+",
  },
];